spring.application.name=BbangPatrol


##### -----JWT start-----
jwt.secret=${JWT_SECRET}
## 18000000 = 300min
jwt.access-token-expiration=18000000
## 604800000 = 7Days
jwt.refresh-token-expiration=604800000
##### -----JWT end-----

##### -----Kakao start-----
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}
##### -----Kakao end-----

## Redis refresh token
REFRESH_TOKEN_EXPIRED_TIME=7