spring.application.name=BbangPatrol

##### -----Database start-----
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT}
##### -----Database end-----

##### -----SQL init start-----
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.sql.init.schema-locations=classpath:schema_.sql
#spring.sql.init.data-locations=classpath:data_.sql
##### -----SQL init end-----

##### -----JWT start-----
jwt.secret=${JWT_SECRET}
## 18000000 = 300min, 86400000 = 1Day
jwt.access-token-expiration=86400000
## 604800000 = 7Days
jwt.refresh-token-expiration=604800000
##### -----JWT end-----

##### -----Kakao start-----
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}
kakao.client.secret=${KAKAO_CLIENT_SECRET}
##### -----Kakao end-----

##### -----Cloudflare R2 start-----
cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.access-key=${R2_ACCESS_KEY_ID}
cloudflare.r2.secret-key=${R2_SECRET_ACCESS_KEY}
cloudflare.r2.bucket-name=${R2_BUCKET_NAME}
cloudflare.r2.public-base-url=${R2_PUBLIC_BASE_URL:}
##### -----Cloudflare R2 end-----

## Redis refresh token
REFRESH_TOKEN_EXPIRED_TIME=7

##### -----Actuator start-----
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
##### -----Actuator end-----
